# Generated by Django 4.2.4 on 2023-09-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(choices=[('option1', 'Mobile'), ('option2', 'Pets'), ('option3', 'Person')], max_length=50)),
                ('type_lost_found', models.BooleanField()),
                ('description', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('option1', 'a'), ('option2', 'b'), ('option3', 'c')], max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
