# Generated by Django 4.2.4 on 2023-10-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_listing_lost_and_found'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='lost_and_found',
            new_name='Type',
        ),
    ]
