# Generated by Django 4.2.4 on 2023-10-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_lost_and_found_listing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.cmss.gov.in%2Fgoverning-body%2F&psig=AOvVaw2Ghh0fc_OSZbjB5p8PvfSJ&ust=1696328331081000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCLi-v8-R14EDFQAAAAAdAAAAABAJ', upload_to='media/listings/images')),
                ('description', models.CharField(max_length=500)),
                ('Type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', max_length=10)),
                ('categorie', models.CharField(choices=[('mobile', 'Mobile'), ('people', 'People'), ('pets', 'Pets')], max_length=50)),
                ('state', models.CharField(choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jammu_kashmir', 'Jammu and Kashmir'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal'), ('andaman_nicobar', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra_nagar_haveli', 'Dadra and Nagar Haveli'), ('daman_diu', 'Daman and Diu'), ('delhi', 'Delhi'), ('lakshadweep', 'Lakshadweep'), ('puducherry', 'Puducherry')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='Enter phone number in format: +1234567890', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='Type',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', max_length=10),
        ),
    ]
