# Generated by Django 4.2.4 on 2023-10-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_listing_people_listing_pets_alter_listing_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='listing_mobile',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='listing_people',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='listing_pets',
            name='Type',
        ),
        migrations.AlterField(
            model_name='listing',
            name='categorie',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('people', 'People'), ('pets', 'Pets')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing_mobile',
            name='categorie',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('people', 'People'), ('pets', 'Pets')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing_people',
            name='categorie',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('people', 'People'), ('pets', 'Pets')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing_pets',
            name='categorie',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('people', 'People'), ('pets', 'Pets')], max_length=50),
        ),
    ]
